user:
  mode: token
  login:
    username:
    password:
  token:
    DEDEUSERID: 520466
    SESSDATA: a31ed5f0%2C1621474470%2Cc44fc*b1
    BILI_JCT: 6c39c5bdb680d473a8f42066c54ae230

home:
  on: true

live:
  on: true

comic:
  on: true
  platform: ios

mail:
  on: true
  user:
  pass:
  host:
  port:

ext:
  on: false
  kafka:
    on: false