user:
  mode: token
  login:
    username:
    password:
  token:
    DEDEUSERID:
    SESSDATA:
    BILI_JCT:

home:
  on: true

live:
  on: true

comic:
  on: true
  platform: ios

mail:
  on: true
  user:
  pass:
  host:
  port:

ext:
  on: false
  kafka:
    on: false